export interface Menu{
    menuId:number;
    menuName:string;
    moduleId?:number;
    parentId:number;
    isSubParent:boolean;
    subParentId:number;
    menuIcon:string;
    menuPath:string;
    menuList:Menu[];
    menuSequence:number;    
    permissionId:number;
    canCreate:boolean;
    canEdit:boolean;
    canDelete:boolean;
    canView:boolean;
    userId:number;
    roleId:number;
    isActive?:boolean
}